import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";
import { Navbar } from "@/app/_components/layout/navbar/navbar";
import { Footer } from "@/app/_components/layout/footer";

const roboto = Roboto({
  weight: ["200", "300", "800"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider
      clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? ""}
    >
      <html lang="en">
        <body className={`relative ${roboto.variable} antialiased bg-background`}>
          <Navbar />
          <main className="flex flex-col overflow-hidden py-30 gap-30 min-h-screen">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
