import type { Metadata } from "next";
import "./globals.css";

import { Nunito } from "next/font/google";
import { Navbar } from "@/app/_components/layout/navbar";
import { Footer } from "@/app/_components/layout/footer";

const roboto = Nunito({
  weight: ["200", "300", "800"],
  display: "swap",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased bg-background`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
